#!/bin/bash
echo " "
echo "---------------------------------"
echo "- S E R V E R -"
echo "---------------------------------"
echo " "
echo "ode name: `uname -n`"
echo "achine name: `uname -m`"
echo "perating System : `uname -o`"
echo "ernel name: `uname -s`"
echo "ernel version: `uname -v`"
echo "ernel release: `uname -r`"
echo "rocessor Type: `uname -p`"
echo "ardware Platform: `uname -i`"
echo " "
echo "---------------------------------"
echo "- M E M O R Y -"
echo "---------------------------------"
echo " "
cat /proc/meminfo | grep MemTotal
echo " "
echo "---------------------------------"
echo "- P R O C E S S O R S -"
echo "---------------------------------"
echo " "
cat /proc/cpuinfo |grep "model name"| nl
echo " "
echo "---------------------------------"
echo "- D I S K  S P A C E -"
echo "---------------------------------"
echo " "
df -h
echo " "
